version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shipgora-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rcahvj2bl5ms"
s3_prefix = "shipgora-app"
region = "us-west-2"
profile = "intelconstruct"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "SecurityGroupIds=\"\" SubnetIds=\"\" proxyHost=\"\" username=\"\" db=\"mysql\" port=\"3306\" region=\"\""
