version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shipgora-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tn2bq8dq5nuq"
s3_prefix = "shipgora-app"
region = "us-east-1"
profile = "remoteyear"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
