AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  0.4 - Building a serverless Laravel App with AWS SAM and Bref-FPM

##########################################################################
#  Globals                                                               #
##########################################################################
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        AWS_BUCKET: !Ref Storage
        AWS_PUBLIC_BUCKET: !Ref Assets
Resources:
##########################################################################
#  S3 Bucket to store static assets                                      #
##########################################################################
  Assets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: php-example-laravel-public-bucket-shipgoo

  Storage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: php-example-laravel-filesystem-bucket-shipo0



##########################################################################
#  Lambda function with PHP runtime provided by layers                   #
##########################################################################
  CatchAllLambdaFunctionLaravel:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function to hosts entire application codebase
      CodeUri: .
      Runtime: provided.al2
      Handler: post/public/index.php #follows our Laravel implementation
      MemorySize: 1024
      Timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
      Tracing: Active
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref Storage
        - S3FullAccessPolicy:
            BucketName: !Ref Assets
      Environment:
        Variables:
          APP_STORAGE: /tmp

      Layers:
        - 'arn:aws:lambda:us-east-1:534081306603:layer:php-82-fpm:21'
      Events:
        DynamicRequestsRoot:
          Type: HttpApi
          Properties:
            Path: /post
            Method: GET
        DynamicRequestsProxy:
          Type: HttpApi
          Properties:
            Path: /post_test
            Method: GET

  UserAllLambdaFunctionLaravel:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function to hosts entire application codebase
      CodeUri: .
      Runtime: provided.al2
      Handler: user/public/index.php #follows our Laravel implementation
      MemorySize: 1024
      Timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
      Tracing: Active
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref Storage
        - S3FullAccessPolicy:
            BucketName: !Ref Assets
      Environment:
        Variables:
          APP_STORAGE: /tmp

      Layers:
        - 'arn:aws:lambda:us-east-1:534081306603:layer:php-82-fpm:21'
      Events:
        DynamicRequestsRoot:
          Type: HttpApi
          Properties:
            Path: /user
            Method: GET
        DynamicRequestsProxy:
          Type: HttpApi
          Properties:
            Path: /user_test
            Method: GET
#
# Outputs show up in the CloudFormation dashboard
#Outputs:
#    Website:
#        Description: 'URL of our function in the *Prod* environment'
#        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'